name: AX6000

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/hanwckf/immortalwrt-mt798x.git
  REPO_BRANCH: openwrt-21.02
  CONFIG_FILE: AX6000.config

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: apt update
      run: sudo -E apt-get update -y

    - name: apt upgrade
      run: sudo -E apt-get upgrade -y

    - name: git clone
      run: |
        git clone -b ${{ env.REPO_BRANCH }} ${{ env.REPO_URL }} openwrt

    - name: Cache openwrt builds
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: 'true'
        prefix: openwrt

    - name: feeds update
      run: |
        cd openwrt
        ./scripts/feeds update -a

    - name: Upgrade golang
      run: |
        cd openwrt
        git clone --depth 1 https://github.com/immortalwrt/packages.git immortalwrt_packages
        rm -r feeds/packages/lang/golang
        cp -r immortalwrt_packages/lang/golang feeds/packages/lang/
        rm -r immortalwrt_packages

    - name: Upgrade luci-app-ssr-plus
      run: |
        rm -r openwrt/feeds/packages/net/xray-core
        rm -r openwrt/feeds/luci/applications/luci-app-ssr-plus
        cd openwrt
        git clone --depth 1 -b master https://github.com/fw876/helloworld.git helloworld
        cp -r helloworld/xray-core feeds/packages/net/
        rm -r helloworld
        git clone --depth 1 -b custom https://github.com/chika0801/helloworld.git helloworld
        cp -r helloworld/luci-app-ssr-plus feeds/luci/applications/
        rm -r helloworld

    - name: feeds install
      run: |
        cd openwrt
        ./scripts/feeds install -a

    - name: Replace the .config file
      run: |
        [ -e $CONFIG_FILE ] && cp ${{ env.CONFIG_FILE }} openwrt/.config

    - name: Customize openwrt configuration
      run: |
        cd openwrt
        sed -i 's/192.168.1.1/192.168.10.1/g' package/base-files/files/bin/config_generate
        sed -i 's#^root::0:0:99999:7:::#root:$1$O73yltLo$SBOqN9kzSHZA5EuKYWXmG/::0:99999:7:::#' package/base-files/files/etc/shadow

    - name: Compile firmware
      run: |
        cd openwrt
        make defconfig
        make download -j8
        make -j$(nproc) || make -j1 || make -j1 V=s

    - name: Check space usage
      if: (!cancelled())
      run: |
        df -hT

    - name: List firmware files
      run: |
        find openwrt/bin/targets/*/*/ -maxdepth 1 -type f -exec du -h {} \;

    - name: Upload firmware files
      uses: actions/upload-artifact@v3
      with:
        name: squashfs-sysupgrade.bin
        path: |
          openwrt/bin/targets/mediatek/mt7986/immortalwrt-mediatek-mt7986-xiaomi_redmi-router-ax6000-stock-squashfs-sysupgrade.bin
          
