name: Fastrhino R66s

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  REPO_BRANCH: openwrt-23.05
  CONFIG_FILE: R66s.config

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: apt update && apt upgrade
      run: |
        sudo apt update -y
        sudo apt upgrade -y

    - name: apt install
      run: |
        sudo apt install -y python3-pyelftools

    - name: git clone
      run: |
        git clone -b ${{ env.REPO_BRANCH }} --depth 1 ${{ env.REPO_URL }} openwrt

    - name: cache openwrt
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: 'true'
        prefix: openwrt

    - name: feeds update
      run: |
        cd openwrt
        ./scripts/feeds update -a

    - name: feeds install
      run: |
        cd openwrt
        ./scripts/feeds install -a

    - name: Customized the .config file
      run: |
        [ -e $CONFIG_FILE ] && cp ${{ env.CONFIG_FILE }} openwrt/.config

    - name: Customized openwrt configuration
      run: |
        cd openwrt
        sed -i 's/192.168.1.1/192.168.10.1/g' package/base-files/files/bin/config_generate
        sed -i 's#^root:::0:99999:7:::#root:$1$O73yltLo$SBOqN9kzSHZA5EuKYWXmG/::0:99999:7:::#' package/base-files/files/etc/shadow

    - name: Compile firmware
      run: |
        cd openwrt
        make defconfig
        make download -j8
        make -j$(nproc) || make -j1

    - name: Show firmware files
      run: |
        find openwrt/bin/targets/*/*/ -maxdepth 1 -type f -exec du -h {} \;

    - name: Upload firmware files
      uses: actions/upload-artifact@v3
      with:
        name: squashfs-sysupgrade.bin
        path: openwrt/bin/targets/*/*/*-squashfs-sysupgrade.img.gz
