name: Fastrhino R66s

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  REPO_BRANCH: master
  CONFIG_FILE: R66s.config

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: apt update
      run: sudo apt update -y

    - name: apt upgrade
      run: sudo apt upgrade -y

    - name: apt install
      run: sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev python3-setuptools

    - name: git clone
      run: |
        git clone -b ${{ env.REPO_BRANCH }} ${{ env.REPO_URL }} openwrt

    - name: Update feeds.conf
      run: |
        cd openwrt
        echo -e 'src-git app_ssrp https://github.com/fw876/helloworld.git' >> feeds.conf.default
        echo -e 'src-git app_passwall https://github.com/xiaorouji/openwrt-passwall.git' >> feeds.conf.default

    - name: Cache openwrt builds
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: 'true'
        prefix: openwrt

    - name: feeds update
      run: |
        cd openwrt
        ./scripts/feeds update -a

    - name: Upgrade luci-theme-argon
      run: |
        cd openwrt
        git clone -b 18.06 --depth 1 https://github.com/jerrykuku/luci-theme-argon.git luci-theme-argon
        rm -r feeds/luci/themes/luci-theme-argon
        cp -r luci-theme-argon feeds/luci/themes/

    - name: feeds install
      run: |
        cd openwrt
        ./scripts/feeds install -a

    - name: Replace the .config file
      run: |
        [ -e $CONFIG_FILE ] && cp ${{ env.CONFIG_FILE }} openwrt/.config

    - name: Customize openwrt configuration
      run: |
        cd openwrt
        sed -i 's/192.168.1.1/192.168.10.1/g' package/base-files/files/bin/config_generate

    - name: Compile firmware
      run: |
        cd openwrt
        make defconfig
        make download -j8
        make -j$(nproc) || make -j1

    - name: List firmware files
      run: |
        find openwrt/bin/targets/*/*/ -maxdepth 1 -type f -exec du -h {} \;

    - name: Upload firmware files
      uses: actions/upload-artifact@v3
      with:
        name: squashfs-sysupgrade.bin
        path: openwrt/bin/targets/rockchip/armv8/immortalwrt-rockchip-armv8-lunzn_fastrhino-r66s-squashfs-sysupgrade.img.gz
