name: Fastrhino R66s

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  REPO_BRANCH: openwrt-23.05
  CONFIG_FILE: R66s.config

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: apt update
      run: sudo apt update -y

    - name: apt upgrade
      run: sudo apt upgrade -y

    - name: apt install
      run: sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

    - name: git clone
      run: |
        git clone -b ${{ env.REPO_BRANCH }} ${{ env.REPO_URL }} openwrt

    - name: Cache openwrt builds
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: 'true'
        prefix: openwrt

    - name: feeds update
      run: |
        cd openwrt
        ./scripts/feeds update -a

    - name: feeds install
      run: |
        cd openwrt
        ./scripts/feeds install -a

    - name: Replace the .config file
      run: |
        [ -e $CONFIG_FILE ] && cp ${{ env.CONFIG_FILE }} openwrt/.config

    - name: Customize openwrt configuration
      run: |
        cd openwrt
        sed -i 's/192.168.1.1/192.168.10.1/g' package/base-files/files/bin/config_generate
        sed -i 's#^root:::0:99999:7:::#root:$1$O73yltLo$SBOqN9kzSHZA5EuKYWXmG/::0:99999:7:::#' package/base-files/files/etc/shadow

    - name: Compile firmware
      run: |
        cd openwrt
        make defconfig
        make download -j8
        make -j$(nproc) || make -j1

    - name: List firmware files
      run: |
        find openwrt/bin/targets/*/*/ -maxdepth 1 -type f -exec du -h {} \;

    - name: Upload firmware files
      uses: actions/upload-artifact@v3
      with:
        name: squashfs-sysupgrade.bin
        path: openwrt/bin/targets/rockchip/armv8/immortalwrt-rockchip-armv8-lunzn_fastrhino-r66s-squashfs-sysupgrade.img.gz
